version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio-server
    ports:
      - "9000:9000"      # API port
      - "9001:9001"      # Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_CONSOLE_ADDRESS: ":9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  # Container to create buckets on startup
  bucket-init:
    image: minio/mc:latest
    container_name: minio-bucket-init
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      RAW_DATA_BUCKET: raw-data
    volumes:
      - ./scripts:/scripts
    working_dir: /scripts
    entrypoint: ["/bin/sh"]
    command: ["init-buckets.sh"]
    restart: "no"

volumes:
  minio_data:
    driver: local

networks:
  default:
    name: minio-network
